# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

RGBLIGHT_ENABLE = yes # Enable RGB
RGB_MATRIX_ENABLE = no # DISABLES RGB MATRIX
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = yes
LTO_ENABLE = yes
REPEAT_KEY_ENABLE = no # Off to save space
COMBO_ENABLE = no
TAP_DANCE_ENABLE = yes

# Alt. Mapping Options
MIRYOKU_ALPHAS = QWERTY
MIRYOKU_EXTRA = COLEMAKDH
MIRYOKU_TAP = QWERTY
MIRYOKU_NAV = INVERTEDT
MIRYOKU_CLIPBOARD = WIN